pipeline {
    agent any

    stages {
        stage('Run Docker Container') {
            steps {
                script {
                 bat 'docker run -d  -e SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/yourdbname -p 8070:8090 spring-boot-microservice:latest'
                }
            }
        }

        stage("test"){
            steps {
                script {
                        echo "Running tests"
                }   
                         }
            
        }

      
    }
}
