pipeline {
    agent any

    stages {
        stage('Run Docker Container') {
            steps {
                script {
                    // Run the container in detached mode mapping ports or volumes as needed
                    //bat 'docker run -d --name strange_elbakyan -p 8070:8090 spring-boot-microservice:latest'
                    bat 'docker run -d --name strange_elbakyan -e SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/yourdbname -p 8070:8090 spring-boot-microservice:latest'
                    //sh 'docker run -p 8070:8090 -e SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/yourdbname  spring-boot-microservice'
                }
            }
        }

       

      
    }
}
